### ISSUE TITLE
HexViewer: View does not exist on disk!

### ISSUE THREAD

**Issue by igorkulman** [facelessuser/HexViewer#48] opened 2016-05-18 12:53 UTC
Running Sublime Text 3 on Windows 10. Trying to use HexViewer after some time, getting an error message saying

`HexViewer: View does not exist on disk!`

**Comment by facelessuser** [comment] 2016-05-18 13:12
This s a duplicate of #39.  Check out #39 for more info.  Recent pull #47 makes this more clear and will be in the next release.

**Closed by facelessuser** 2016-05-18 13:12 UTC
Labels: Duplicate
